 @ECHO OFF
SET YT-PATH=.
:START
IF "%YT-PATH%"=="." (ECHO SAVING TO: "CURRENT DIRECTORY") ELSE (ECHO SAVING TO: "%YT-PATH%")
SET /P YT-URL="LINK? (ENTER P TO SET A DIFFERENT SAVE PATH / C TO EXIT) "
IF "%YT-URL%"=="P" SET /P YT-PATH="SAVE WHERE? (ENDING WITHOUT A \)"
IF "%YT-URL%"=="p" SET /P YT-PATH="SAVE WHERE? (ENDING WITHOUT A \)"
IF "%YT-URL%"=="C" GOTO END
IF "%YT-URL%"=="c" GOTO END
IF "%YT-URL%"=="" ECHO LINK CAN'T BE EMPTY
REM RUN WHATEVER YT-DLP COMMANDS/OPTIONS
YT-DLP -f "ba*+bv*" -P "%YT-PATH%" "%YT-URL%"
REM "REM" OUT THE PAUSE WHEN YOU HAVE IT WORKING THE WAY YOU WANT
PAUSE
CLS
GOTO START
:END
